language: php
php:
  - "5.5"

install:
   - wget http://getcomposer.org/composer.phar
   - sudo chown root.root composer.phar
   - sudo mv composer.phar /usr/bin/composer
   - sudo chmod +x /usr/bin/composer
   - composer --profile --prefer-source --no-interaction install

# Acceptance tests
before_script:
  - sudo apt-get install nginx
  - sudo cp -f ./config/nginx/travis.conf /etc/nginx/nginx.conf
  - sudo cp -f ./config/nginx/travis.vhost /etc/nginx/sites-available/default
  - sudo mkdir /var/www/
  - sudo ln -s  $(pwd) /var/www/restapi
  - HTTPDUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
  - sudo chown -R .$HTTPDUSER *
  - sudo service nginx restart
  # php5 fpm
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # phalcon
  - sh config/phalcon.sh

script:
  - mkdir -p build/logs
  - sh test/phpunit.sh
  - sh test/behat.sh -p ci
after_script:
  - sh test/coveralls.sh

notifications:
  email: "snepote@gmail.com"
